language: scala
sudo: true
scala:
- 2.11.6
jdk:
- oraclejdk8
services:
  - mysql
before_script:
  - mysql -e "create database IF NOT EXISTS testorama;" -uroot
  - export BOXFUSE_DATABASE_URL="jdbc:mysql://localhost/testorama"
  - export BOXFUSE_DATABASE_USER="root"
  - export BOXFUSE_DATABASE_PASSWORD=""
install: true

